with open('24_160622.txt') as f:
    data = f.read().rstrip()
    data = data.replace('ZXY', '*').replace('ZYX', '*')
    data = data.replace('ZXY', '*').replace('ZYX', '*')
    data = data.replace('ZXY', '*').replace('ZYX', '*')
    data = data.replace('X', ' ').replace('Y', ' ').replace('Z', ' ')
    data = data.replace('X', ' ').replace('Y', ' ').replace('Z', ' ')
    data = data.replace('X', ' ').replace('Y', ' ').replace('Z', ' ')
    data = data.split()
    print(len(max(data, key=len)))